#ifndef _SYSTEM_H_
#define _SYSTEM_H_

#define PRODUCTNAME   "EBCTRL2-LA-0044"
#define VERSION_NUM   "CB171_T1.0.C"	     //系统版本号
#define VERSION_DATE   "2016.01.05"			 //系统版本更新日期
	


typedef enum
{
	
	TEST,
	GPIO_INIT,
	WAIT_CARD,
	WAIT_KEY,
	WAIT_CARD_KEY,
	FINDED_CARD, //已经找到卡
	INPUT_CARD_KEY,//在刷卡存包时输入密码的状态
	INPUT_CARD_KEY_AGAIN,//在刷卡存包时再次输入密码的状态
//	INPUT_CARD_KEY_SURE,//在刷卡存包时确认输入的密码

	OUTPUT_CARD_KEY,//在刷卡取包时输入密码的状态
	OUTPUT_CARD_KEY_AGAIN,//在刷卡取包时再次输入密码的状态
//	OUTPUT_CARD_KEY_SURE,//在刷卡取包时确认输入的密码

	WAIT_SURE_KEY,//四位密码输入完成，等待按下确认按键
	PASSW_INPUT_KEY,//密码存包第一次输入密码
	PASSW_INPUT_KEY_AGAIN,//密码存包第二次输入密码
	PASSW_INPUT_KEY_SURE,//密码存包确认密码
	
	PRESS_OUT_KEY,//主界面按下“取”键
	OUT_INPUT_BOXNUM,//"取"输入箱号
	OUT_INPUT_PASSW,//“取”输入密码
	
	
	SCAN_KEY,
	INPUT_BOXNUM,
	INPUT_BOXKEY,	
	SET_KEY_BOXNUM,
	SET_KEY_OLD_BOXKEY,
	SET_KEY_NEW_BOXKEY,
	SET_KEY_SURE_BOXKEY,
	
	ENTER_MAIN_MENU,
	CHECK_POWER_ON_CHARGE,
	SYS_INIT,
	POWER_ON_CHARGE,
	POWER_ON_CHARGE_FINISH,
	SHOW_WELCOME,
	MAIN_MENU,
	DEVICE_CHARGE,
	DEVICE_CHARGE_FINISH,
	WAIT_RETURN_MAIN_MENU,
	WAIT_POWER_OFF,
	POWER_OFF,
	POWER_OFF_CTRL,
	CHECK_POWER_OFF_CHARGE,
	BATTERY_LOW_WARNING,
	WAIT_RETURN_FROM_CONNECT_STATE,

	GET_GPS_INFO,
	GPS_INFO_RESULT_DEAL,
	SHOW_DEV_INIT_GPS_RESULT,
	
	DEV_START_GPRS_CONNECT_TEST,
	GPRS_CONNECT_TEST_VERIFY_ERR,
	SHOW_DEV_START_GPRS_CONNECT_TEST_RESULT,
	
	/***注册功能***/
	REG_FUN_WAIT_VOLTAGE,
	REG_FUN_INIT_DATA,
	REG_FUN_WAIT_REG,
	REG_FUN_SELECT_HOLE,
	REG_FUN_BEGIN_CHECK,
	REG_FUN_CHECKING,
	REG_FUN_ERR_WAIT_SELECT,

	/***网路测试功能***/
	QUICK_TEST_FUN_WAIT_VOLTAGE,
	COMPLETE_TEST_FUN_WAIT_VOLTAGE,
	QUICK_TEST_FUN_CHECK_LEAK,
	QUICK_TEST_FUN_LEAK_ERROR,
	QUICK_TEST_FUN_TESTING,
	COMPLETE_TEST_FUN_BEGIN_TEST,
	COMPLETE_TEST_FUN_TESTING,
	NET_TEST_FUN_SHOW_RESULT,
	NET_TEST_FUN_SHOW_ERR_LIST,

	/***雷管删除功能***/
	DET_DELE_FUN_MODEL_SELECT,
	DET_DELE_FUN_WAIT_MAKE_SURE_DELE_ALL,
	DET_DELE_FUN_DET_LOADING,
	DET_DELE_FUN_WAIT_RETURN_MODEL_SELECT,
	DET_DELE_FUN_SHOW_ERR_LIST,
	DET_DELE_FUN_SELECT_ERR_DET,
	DET_DELE_FUN_INPUT_START_NUM,
	DET_DELE_FUN_INPUT_END_NUM,
	DET_DELE_FUN_START_NUM_ERR,
	DET_DELE_FUN_END_NUM_ERR,
	DET_DELE_FUN_MAKE_SURE,
	
	/***延期修改功能***/
	DLY_MODIFY_FUN_INPUT_START_NUM,
	DLY_MODIFY_FUN_INPUT_END_NUM,
	DLY_MODIFY_FUN_INPUT_HOLE_INSIDE_NUM,
	DLY_MODIFY_FUN_INPUT_START_DLY,
	DLY_MODIFY_FUN_INPUT_HOLE_INTERVAL_DLY,
	DLY_MODIFY_FUN_INPUT_HOLE_INSIDE_DLY,
	DLY_MODIFY_FUN_CALC_HOLE_DLY,
	DLY_MODIFY_FUN_START_NUM_ERR,
	DLY_MODIFY_FUN_END_NUM_ERR,
	DLY_MODIFY_FUN_HOLE_INSIDE_NUM_ERR,
	DLY_MODIFY_FUN_START_DLY_ERR,
	DLY_MODIFY_FUN_HOLE_INTERVAL_DLY_ERR,
	DLY_MODIFY_FUN_HOLE_INSIDE_DLY_ERR,
	DLY_MODIFY_FUN_DLY_LOADING,
	DLY_MODIFY_FUN_SHOW_NET_LIST,
	
	/***单发延期快速修改功能***/
	DLY_FAST_MODIFY_FUN_DET_SELECT,
	DLY_FAST_MODIFY_FUN_INPUT_DLY,
	DLY_FAST_MODIFY_FUN_DLY_ERR,
	
	/***系统信息功能***/
	SYSTEM_INFO_FUN_MENU_SELECT,
	SYSTEM_INFO_FUN_SHOW_DEV_INFO,
	SYSTEM_INFO_FUN_DET_TYPE_SELECT,
	SYSTEM_INFO_FUN_DET_TYPE_SELECT_SAME,
	SYSTEM_INFO_FUN_DET_TYPE_SELECT_WAIT_DELE_DET,
	SYSTEM_INFO_FUN_DET_TYPE_SELECT_MAKE_SURE,
	SYSTEM_INFO_FUN_WAIT_RETURN_MENU_SELECT,
	SYSTEM_INFO_FUN_DKEY_MENU_SELECT,
	SYSTEM_INFO_FUN_INFO_INTO_DEVICE_MAKE_SURE,
	SYSTEM_INFO_FUN_WAIT_RETURN_DKEY_MENU,
	SYSTEM_INFO_FUN_INFO_INTO_DEVICE_DOING,
	SYSTEM_INFO_FUN_INFO_INTO_DEVICE_VERIFY_ERR,
	SYSTEM_INFO_FUN_INFO_INTO_DEVICE_LOADING,
	SYSTEM_INFO_FUN_INFO_INTO_DKEY_MAKE_SURE,
	SYSTEM_INFO_FUN_INFO_INTO_DKEY_DOING,
	SYSTEM_INFO_FUN_DELETE_DEKY_INFO_MAKE_SURE,
	SYSTEM_INFO_FUN_SELF_TESTING,
	SYSTEM_INFO_FUN_SELF_TEST_WAIT_HV_SW,
	SYSTEM_INFO_FUN_WAIT_SELF_TEST_BLAST_SIGNAL,
	
	SYSTEM_INFO_FUN_SHOW_SAFEMONITOR_FUN_MENU,
	SYSTEM_INFO_FUN_MAKE_SURE_GPRS_TEST,
	SYSTEM_INFO_FUN_GPRS_CONNECT_TEST,
	SYSTEM_INFO_FUN_SHOW_GPRS_TEST_RESULT,
	SYSTEM_INFO_FUN_MAKE_SURE_SEND_BLASTER_RECORD,
	SYSTEM_INFO_FUN_SEND_BLASTER_RECORD,
	SYSTEM_INFO_FUN_SHOW_SEND_BLASTER_RECORD_RESULT,
	
	SYSTEM_INFO_FUN_WAIT_RETURN_SHOW_SAFEMONITOR_FUN_MENU,
	SYSTEM_INFO_FUN_SHOW_BLASTE_FIRE_RECORDER,
	
	SYSTEM_INFO_FUN_DKEY_PWD_MODIFY_INPUT_USERNAME,
	SYSTEM_INFO_FUN_DKEY_PWD_MODIFY_INPUT_OLDPWD,
	SYSTEM_INFO_FUN_DKEY_PWD_MODIFY_INPUT_NEWPWD1,
	SYSTEM_INFO_FUN_DKEY_PWD_MODIFY_INPUT_NEWPWD2,
	SYSTEM_INFO_FUN_DKEY_PWD_MODIFY_RESULT,
	
	SYSTEM_INFO_FUN_WAIT_RS485_NET_FIXED,
	SYSTEM_INFO_FUN_GET_NET_CONNECT_INFO,
	SYSTEM_INFO_FUN_SHOW_NET_CONNECT_INFO_RESULT,
	SYSTEM_INFO_FUN_SHOW_NET_CONNECT_INFO_LIST,

	/***起爆流程功能***/
	BLASTER_FUN_CHECK_DKEY,
	BLASTER_FUN_BATTARY_LOW,
	BLASTER_FUN_INPUT_USERNAME,
	BLASTER_FUN_INPUT_PASSWORD,
	BLASTER_FUN_USERNAME_PASSWORD_ERR,
	BLASTER_FUN_QUICK_TEST_WAIT_VOLTAGE,
	BLASTER_FUN_BEGIN_QUICK_TEST,
	BLASTER_FUN_QUICK_TESTING,
	BLASTER_FUN_SHOW_QUICK_TEST_REPORT,
	BLASTER_FUN_SHOW_QUICK_TEST_ERR_LIST,
	BLASTER_FUN_WAIT_OPEN_HV_BUTTON,
	BLASTER_FUN_WAIT_HV_PROTECT_READY,
	BLASTER_FUN_WAIT_HV_PROTECT_READY_RETRY,
	BLASTER_FUN_BEGIN_COMPLETE_TEST,
	BLASTER_FUN_COMPLETE_TESTING,
	BLASTER_FUN_SHOW_BUSLEAKCURRENT_ERR,
	BLASTER_FUN_SHOW_COMPLETE_TEST_REPORT,
	BLASTER_FUN_SHOW_COMPLETE_TEST_ERR_LIST,
	BLASTER_FUN_WAIT_START_CHARGE,
	BLASTER_FUN_CHARGING,
	BLASTER_FUN_CHARGE_FINISH,
	BLASTER_FUN_SEND_SIGNAL_NUMBER_5,
	BLASTER_FUN_SEND_SIGNAL_NUMBER_4,
	BLASTER_FUN_SEND_SIGNAL_NUMBER_3,
	BLASTER_FUN_SEND_SIGNAL_NUMBER_2,
	BLASTER_FUN_SEND_SIGNAL_NUMBER_1,
	BLASTER_FUN_SEND_SIGNAL,
	BLASTER_FUN_SEND_SIGNAL_END,
	BLASTER_FUN_SAVE_RECORD,
	BLASTER_FUN_SEND_BLASTER_FIRE_RECORD_TO_DKEY,
	BLASTER_FUN_SHOW_SEND_BLASTER_FIRE_RECORD_TO_DKEY_RESULT,
	BLASTER_FUN_GPRS_SEND_BLASTER_FIRE_RECORD,
	BLASTER_FUN_FINISH,
	BLASTER_FUN_WAIT_EXIT_MAKE_SURE,
	
	BLASTER_FUN_DKEY_SAVE_RECORD,
	BLASTER_FUN_GPRS_SAVE_RECORD,
	
	/***注册列表显示功能***/
	NET_LIST_FUN_SHOW_INFO,
	
	/***MODBUS***/
	MB_FUN_DET_AND_DLY_INFO_LOADING,
	MB_FUN_DET_INFO_LOADING,
	MB_FUN_DLY_INFO_LOADING
	
}SYS_STATE;



#endif

//_FUN_WAIT_EXIT_MAKE_SURE,
//	
//	BLASTER_FUN_DKEY_SAVE_RECORD,
//	BLASTER_FUN_GPRS_SAVE_RECORD,
//	
//	/***娉ㄥ唽鍒楄〃鏄剧ず鍔熻兘***/
//	NET_LIST_FUN_SHOW_INFO,
//	
//	/***MODBUS***/
//	MB_FUN_DET_AND_DLY_INFO_LOADING,
//	MB_FUN_DET_INFO_LOADING,
//	MB_FUN_DLY_INFO_LOADING
//	
//}SYS_STATE;



//#endif

